const LOCAL_GENSHIN_DATA = {
    characters: [
        { name: "Arlecchino", vision: "Pyro", weapon: "Arme d'hast", rarity: 5, elevation: "DGT CRIT", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Arlecchino.png", anniversaire: "22/8", nation: "Snezhnaya", affiliation: "Fatui", constellation: "Ignis Purgatorio", description: "Quatriéme Exécutrice des Fatui, Arlecchino est une diplomate posée et impitoyable. Pour les enfants du Foyer de l'âtre, elle est Leur « Pére » redoutée mais fiable.", normale: "Invitation au supplice", desc: "Attaque normale <br>Enchaine jusqu'à 6 coups de lance.<br><br>Attaque chargée <br>Consomme de l'endurance pour charger vers un ennemi proche et le trancher une fois. <br>En maintenant le bouton, Arlecchino consomme de l'endurance pour se déplacer rapidement pendant un maximum de 5 s.<br><br>Attaque plongeante <br>Plonge depuis les airs pour frapper le sol, infligeant des DGT aux ennemis en chemin et des DGT de zone à l'impact. <br><br>Masque de la mort rouge <br>Lorsque Arlecchino est sous l'effet d'un engagement vital dont la valeur est supérieure ou égale å 30 % de ses PV max, ele entre dans l'état Masque de la mort rouge et ses attaques normales, chargées et plongeantes sont imprégnées de DGT Pyro ne pouvant pas étre enchantés. <br>Sous l'effet du masque de la mort rouge, toucher un ennemi avec une attaque normale augmente les DGT de l'attaque d'une valeur équivalant à un pourcentage de I'ATQ d'Arlecchino multipliée par le pourcentage de son engagement vital actuel et consomme 7,5 % de l'engagement vital actuel. Un engagement vital peut étre consommé de cette manière une fois toutes les 0,03 s. Lorsqu'un engagement vital est consommé de cette manière, le TdR de la compétence élémentaire « Pulvérisation totale » diminue de 0,8s" },
        { name: "Furina", vision: "Hydro", weapon: "Épée à une main", rarity: 5, elevation: "Taux CRIT", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Furina.png", anniversaire: "13/10", nation: "Fontaine", affiliation: "Cour de Fontaine", constellation: "Animula Choragi", description: "Le point central absolu de la scene du jugement, jusqu'aux applaudissements finaux." },
        { name: "Zhongli", vision: "Géo", weapon: "Arme d'hast", rarity: 5, elevation: "Bonus de DGT Géo", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Zhongli.png", anniversaire: "31/12", nation: "Liyue", affiliation: "Port de Liyue", constellation: "Lapis Dei", description: "Une mystérieuse relation du Funérarium Wangsheng, aux connaissances aussi variées qu'étendues." },
        { name: "Raiden Shogun", vision: "Électro", weapon: "Arme d'hast", rarity: 5, elevation: "Recharge d'énergie", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Shougun.png", anniversaire: "26/6", nation: "Inazuma", affiliation: "Cité d'Inazuma", constellation: "Imperatrix Umbrosa", description: "Son Excellence, la toute-puissante Narukami Ogosho, qui a promis au peuple d'lnazuma une éternité immuable." },
        { name: "Nahida", vision: "Dendro", weapon: "Catalyseur", rarity: 5, elevation: "Maitrise élémentaire", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Nahida.png", anniversaire: "27/10", nation: "Sumeru", affiliation: "Ville de Sumeru", constellation: "Sapientia Oromasdis", description: "Une oiselle en cage isolée dans les profondeurs du Sanctuaire de Surasthana qui ne peut voir le monde que dans ses réves." },
        { name: "Diluc", vision: "Pyro", weapon: "Épée à deux mains", rarity: 5, icon: "https://enka.network/ui/UI_AvatarIcon_Side_Diluc.png", anniversaire: "30/4", nation: "Mondstadt", affiliation: "Domaine de l'Aurore", constellation: "Noctua", description: "Un jeune noble possédant la blupart des entreprises du vin de Mondstadt. Nul ne saurait sous-estimer sa richesse, sa réputation et ses capacités.", elevation: "Taux CRIT" },
        { name: "Kaedehara Kazuha", vision: "Anémo", weapon: "Épée à une main", rarity: 5, icon: "https://enka.network/ui/UI_AvatarIcon_Side_Kazuha.png", anniversaire: "29/10", nation: "Inazuma", affiliation: "Flotte du Crux", constellation: "Acer Palmatum", description: "Un samourai errant d'lnazuma qui fait actuellement partie dela Flotte du Crux. Une ame douce et insouciante dont le cæur cache de nombreuses blessures.", elevation: "Maitrise élémentaire" },
        { name: "Kamisato Ayaka", vision: "Cryo", weapon: "Épée à une main", rarity: 5, elevation: "DGT CRIT", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Ayaka.png", anniversaire: "28/9", nation: "Inazuma", affiliation: "Commission Culturelle", constellation: "Grus Nivis", description: "Fille du Clan Kamisato de la Commission culturelle. Digne et élégante, mais aussi sage et forte." },
        { name: "Neuvillette", vision: "Hydro", weapon: "Catalyseur", rarity: 5, elevation: "DGT CRIT", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Neuvillette.png", anniversaire: "18/12", nation: "Fontaine", affiliation: "Cour de Fontaine", constellation: "Leviathan Judicator", description: "Le juge supreme de Fontaine, également connu comme I'iudex, est réputé pour son impartialité sans faille." },
        { name: "Hu Tao", vision: "Pyro", weapon: "Arme d'hast", rarity: 5, elevation: "DGT CRIT", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Hutao.png", anniversaire: "15/7", nation: "Liyue", affiliation: "Funérarium Wangsheng", constellation: "Papilio Charontis", description: "La 77e directrice du Funérarium Wangsheng, qui redonne un coup de jeune à la gestion des affaires funéraires de Liyue." },
        { name: "Xiao", vision: "Anémo", weapon: "Arme d'hast", rarity: 5, elevation: "TAUX CRIT", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Xiao.png", anniversaire: "17/4", nation: "Liyue", affiliation: "Adeptes de Liyue", constellation: "Alatus Nemeseos", description: "Un des Adeptes de Liyue, aussi connu sous le nom de « Dompteur de démons » et « Général des Yakshas ." },
        { name: "Cyno", vision: "Électro", weapon: "Arme d'hast", rarity: 5, elevation: "DGT CRIT", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Cyno.png", anniversaire: "23/6", nation: "Sumeru", affiliation: "Temple du Silence", constellation: "Lupus Aureus", description: "Le général mahamatra chargé de superviser les chercheurs de l'Académie. On dit que lorsqu'il se met au travail, il est encore plus efficace que le grand vayuvyastra fabriqué par le Kshahrewar." },
        { name: "Navia", vision: "Géo", weapon: "Épée à deux mains", rarity: 5, elevation: "DGT CRIT", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Navia.png", anniversaire: "16/8", nation: "Fontaine", affiliation: "Spina di Rosula", constellation: "Rosa Multiflora", description: "L'actuelle présidente de Spina di Rosula, qui est une patronne adorable, dévouée et formidable." },
        { name: "Jean", vision: "Anémo", weapon: "Épée à une main", rarity: 5, elevation: "Bonus de soins", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Qin.png", anniversaire: "14/3", nation: "Mondstadt", affiliation: "Ordre de Favonius", constellation: "Leo Minor", description: "Le Chevalier au Pissenlit, loyal et rigoureux, et la Grande Maitresse suppléante de l'Ordre de Favonius." },
        { name: "Qiqi", vision: "Cryo", weapon: "Épée à une main", rarity: 5, elevation: "Bonus de soins", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Qiqi.png", anniversaire: "3/3", nation: "Liyu", affiliation: "Cottage Bubu", constellation: "Pristina Nola", description: "Qiqi est une jeune apprentie du Cottage Bubu, en charge notamment de la récolte des herbes médicinales. C'est également un zombie au teint blafard et aux mots comptés." },
        { name: "Mona", vision: "Hydro", weapon: "Catalyseur", rarity: 5, elevation: "Recharge d'énergie", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Mona.png", anniversaire: "31/8", nation: "Mondstadt", affiliation: "Cité de Mondstadt", constellation: "Astrolabos", description: "Jeune astromancienne mystérieuse, Mona se surnomme elle-même « la grande astromancienne Mona », et fait preuve d'une force singuliére et d'une érudition hors norme qui ne désavouent pas cette appellation." },
        { name: "Keqing", vision: "Électro", weapon: "Épée à une main", rarity: 5, elevation: "DGT CRIT", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Keqing.png", anniversaire: "20/11", nation: "Liyue", affiliation: "Sept Étoiles de Liyue", constellation: "Trulla Cementarii", description: "L'Alioth, l'une des Sept Étoiles de Liyue. L'Alioth critique à mots couverts l'idée que Liyue suive à la lettre La parole du Souverain de la Roche, mais ce dernier apprécie justement ce genre de personnes." },
        { name: "Venti", vision: "Anémo", weapon: "Arc", rarity: 5, elevation: "Recharge d'énergie", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Venti.png", anniversaire: "16/6", nation: "Mondstadt", affiliation: "Cité de Mondstadt", constellation: "Carmen Dei", description: "Un des nombreux bardes de Mondstadt, qui aime à se promener dans tous les recoins de la cité." },
        { name: "Klee", vision: "Pyro",  weapon: "Catalyseur", rarity: 5, elevation: "Bonus de DGT Pyro", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Klee.png", anniversaire: "27/7", nation: "Mondstadt", affiliation: "Ordre deFavonius", constellation: "Trifolium", description: "Une invitée réguliére des cellules de l'Ordre de Favonius, et également la maitresse des explosions à Mondstadt, où on la surnomme « le soleil fuyant »." },
        { name: "Tartaglia", vision: "Hydro", weapon: "Arc", rarity: 5, elevation: "Bonus de DGT Hydro", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Tartaglia.png", anniversaire: "20/7", nation: "Snezhnaya", affiliation: "Fatui", constellation: "Monoceros Caeli", description: "Le 11e Exécuteur des Fatui, appelé « Tartaglia ». Il s'est fait connaitre avoir gagné des millier de combats." },
        { name: "Albedo", vision: "Géo", weapon: "Épée à une main", rarity: 5, elevation: "Bonus de DGT Géo", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Albedo.png", anniversaire: "13/9", nation: "Mondstadt", affiliation: "Ordre de Favonius", constellation: "Princeps Cretaceus", description: "Génie connu sous le surnom de « Kreideprinz », Albedo est l'alchimiste en chef et le capitaine des enquéteurs de l'Ordre de Favonius." },
        { name: "Ganyu", vision: "Cryo", weapon: "Arc", rarity: 5, elevation: "DGT CRIT", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Ganyu.png", anniversaire: "2/12", nation: "Liyue", affiliation: "Pavillon Yuehai", constellation: "Sinae Unicornis", description: "'Secrétaire du Pavilion Yuehai ; du sang de Qilin, la créature mythique, coule dans ses veines." },
        { name: "Eula", vision:"Cryo", weapon: "Épée à deux mains", rarity: 5, elevation: "DGT CRIT", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Eula.png", anniversaire: "25/10", nation: "Mondstadt", affiliation: "Ordre de Favonius", constellation: "Aphros Delos", description: "Le « Chevalier aux Embruns », né de l'ancien Clan Lawrence, capitaine de l'unité de reconnaissance des chevaliers de l'Ordre de Favonius de Mondstadt. Que cette descendante de la noblesse d'antan ait rejoint les chevaliers de l'Ordre, l'ennemi jusqu'alors juré de la famille, demeure un mystére aux yeux de beaucoup." },
        { name: "Yoimiya", vision: "Pyro", weapon: "Arc", rarity: 5, elevation: "TAUX CRIT", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Yoimiya.png", anniversaire: "21/6,", nation: "Inazuma", affiliation: "Feux de Naganohara", constellation: "Carassius Auratus", description: "Propriétaire des « Feux de Naganohara Connue sous le nom de « Reine du festival d'été », elle excelle dans son art de créer des feux d'artifice qui symbolisent les espoirs et les rêves des gens." },
        { name: "Sangonomiya Kokomi", vision: "Hydro", weapon: "Catalyseur", rarity: 5, elevation: "Bonus de DGT Hydro", icon: "https://enka.network/ui/UI_AvatarIcon_Side_Kokomi.png", anniversaire: "22/2", nation: "Inazuma", affiliation: "Île de Watatsumi", constellation: "Dracaena Somnolenta", description: "La Prétresse divine de l'ile de Watatsumi, une jeune femme gérant toutes les affaires de l'ile." }
    ],
    weapons: [
        { name: "Mort-du-Loup", type: "Épée à deux mains", rarity: 5, icon: "https://enka.network/ui/UI_EquipIcon_Claymore_Wolfmound.png", location: "Vœux", },
        { name: "Coupeur de l'ondine", type: "Épée à une main", rarity: 5, icon: "https://enka.network/ui/UI_EquipIcon_Sword_Morax.png", location: "Vœux" },
        { name: "Bâton de Homa", type: "Arme d'hast", rarity: 5, icon: "https://enka.network/ui/UI_EquipIcon_Pole_Homa.png", location: "Vœux" },
        { name: "Arc d'Amos", type: "Arc", rarity: 5, icon: "https://enka.network/ui/UI_EquipIcon_Bow_Amos.png", location: "Vœux", main: "ATK de base", sub: "ATQ%", names: "Flèche de la volonté", effect: "• Augmente les DGT infligés par les attaques normales et les attaques chargées de 12/15/18/21/24%. Les DGT augmentent de 8/10/12/14/16 % toutes les 0,1 s aprés avoir tiré une fléche d'attaque normale ou chargée. Cet effet peut étre cumulé 5 fois maximum.", description: "Un arc extrémement ancien. Méme si son maitre d'origine n'est plus, on sent encore son pouvoir, drainé de tous les étres de ce monde. Plus l'objet de vos désirs se trouve loin, et meilleure est sa puissance." },
        { name: "Splendeur de l'azur", type: "Catalyseur", rarity: 5, icon: "https://enka.network/ui/UI_EquipIcon_Catalyst_Morax.png", location: "Vœux" },
        { name: "Aigue-marine de Makhaira", type: "Épée à deux mains", rarity: 4, icon: "https://enka.network/ui/UI_EquipIcon_Claymore_Pleroma.png", location: "Forge" },
        { name: "Épée de Favonius", type: "Épée à une main", rarity: 4, icon: "https://enka.network/ui/UI_EquipIcon_Sword_Zephyrus.png", location: "Vœux" },
        { name: "Histoire des chasseurs de dragon", type: "Catalyseur", rarity: 3, icon: "https://enka.network/ui/UI_EquipIcon_Catalyst_Pulpfic.png", location: "Vœux", names: "Héritage", effect: "• Augmente l'ATQ de 24/30/36/42/48 % pendant 10 s après un changement de personnage. Cet effet peut étre déclenché une fois toutes les 20 s. <br><br>L'histoire de cinq hérosnartant å la chasse au dragon. L'ouvrage est mal écrit et particuliérement incohérent. Sa valeur réside dans les nombreuses leqons que l'on peat tirer de l'échec" }
    ],
    artifacts: [
        { name: "Fleur du Noble", rarity: 5, type: "Fleur de la vie", icon: "https://enka.network/ui/UI_RelicIcon_15003_4.png", location: "Donjon", names: "Ancien rituel royal :", effect: "Set de 2 piéce(s) : Augmente les DGT infligés par le déchainement élémentaire de 20 %. <br>Set de 4 piéce(s) : Augmente l'ATQ de tous les personnages de l'équipe de 20 % pendant 12 s aprés un déchainement élémentaire. Cet effet est non cumulable. <br>Une fleur en soie bleue, souvent portée tors d'événements officiels. Son aspect est resté le même que le jour où elle a été cueillie." }
        
    ]
};
